FROM debian:bookworm

WORKDIR /home/tester

COPY ../install_depthai.sh /home/tester/install_depthai.sh

RUN chmod +x /home/tester/install_depthai.sh

RUN apt update && apt install -y bash sudo

CMD ["/home/tester/install_depthai.sh"]
