FROM ubuntu:jammy

WORKDIR /home/tester

# Copy script into the container
COPY docs/install_depthai.sh /home/tester/install_depthai.sh

# Make script executable
RUN chmod +x /home/tester/install_depthai.sh

# Install dependencies (modify if needed based on script requirements)
RUN apt update && apt install -y bash sudo

# Run the script when the container starts
CMD ["/home/tester/install_depthai.sh"]
