FROM ubuntu:jammy

WORKDIR /home/tester

COPY /docs/install_depthai.sh /home/tester/install_depthai.sh

RUN chmod +x /home/tester/install_depthai.sh

RUN apt update && apt install -y bash sudo

CMD ["/home/tester/install_depthai.sh"]
