#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LUXONIS_DEPTHAI_HOME="$(dirname "$SCRIPT_DIR")"
DEPTHAI_DIR="$LUXONIS_DEPTHAI_HOME/depthai"
VENV_DIR="$LUXONIS_DEPTHAI_HOME/venv"
echo "running demo app"
echo "$SCRIPT_DIR"
pwd

if [ "$LUXONIS_DEPTHAI_HOME" = "" ]; then
  echo ':::::::::::::::::::::::::::::::::::::::'
  echo "Something is worng."
  echo "SCRIPT_DIR = $SCRIPT_DIR"
  echo "LUXONIS_DEPTHAI_HOME = $LUXONIS_DEPTHAI_HOME"
  echo '\nLSCRIPT_DIR is probably wrong, see:.\n'
  echo 'Using following script to find the location of this script.'
  echo 'SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )'
  echo "https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script"
  echo ':::::::::::::::::::::::::::::::::::::::'
  exit 1
fi

# check depthai directory exists
if [ -d "$DEPTHAI_DIR" ]; then
  echo "OK. Depthai dir exists on $DEPTHAI_DIR."
else
  echo "Depthai repo should be on $LUXONIS_DEPTHAI_HOME/$APP_NAME, but it does not exist."
  echo "git clone depthai in this directory, or use the installation script again."
  echo "git clone https://github.com/luxonis/depthai.git $LUXONIS_DEPTHAI_HOME/$APP_NAME"
  exit 3
fi

# check venv exists
if [ -d "$VENV_DIR" ]; then
  echo "OK. Virtual environment dir exists on $VENV_DIR."
else
  echo "Virtual environment not found ok $VENV_DIR"
  echo "Re-run the demo app installation script."
  exit 3
fi

source "$VENV_DIR/bin/activate"
echo "running launcher with python version"
echo python --version
python "$DEPTHAI_DIR"/launcher/launcher.py
